######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 21 14:53:01 2017
######################################################################

TEMPLATE = app
TARGET = holabinario
DEPENDPATH += .
INCLUDEPATH += . ../include

# Input
SOURCES += holafuncion.cpp holamain.cpp
