######################################################################
# Automatically generated by qmake (3.0) dom. nov. 19 00:35:21 2017
######################################################################

TEMPLATE = app
TARGET = holabinario
INCLUDEPATH += . ../include
QT += widgets

# Input
SOURCES += holafuncion.cpp holamain.cpp
